name: Train → Build & Push Docker (by request)

on:
  workflow_dispatch:
    inputs:
      dataset_url:
        description: "CSV directo (secure_url de Cloudinary)"
        required: true
      label:
        description: "Tag de la imagen Docker (p.ej. 10k, 5k, 2_5k)"
        required: true

jobs:
  train-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install training deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install numpy==1.23.5 pandas==1.5.3 scikit-learn==1.2.2 joblib==1.3.2
          pip install fastapi==0.95.2 pydantic==1.10.12 uvicorn==0.22.0 requests==2.31.0

      - name: Download dataset
        run: |
          mkdir -p data
          echo "Downloading: ${{ inputs.dataset_url }}"
          curl -L "${{ inputs.dataset_url }}" -o data/creditcard.csv
          head -n 3 data/creditcard.csv || true
          wc -l data/creditcard.csv || true

      - name: Train model
        run: |
          python model/train.py
          ls -lh model/

      - name: Prepare Docker context
        run: |
          mkdir -p docker_ctx/model
          cp Dockerfile app.py requirements.txt docker_ctx/
          cp model/creditcard-v1.joblib docker_ctx/model/creditcard-v1.joblib

      - name: Docker login (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./docker_ctx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ccfd:${{ inputs.label }}
